server:
  port: 8080

spring:
  application:
    name: utility-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false;
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET}

notification:
  service-url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}

logging:
  level:
    ru.isu.cityinfra: DEBUG
    org.springframework.web: INFO